### ISSUE TITLE
 where is the title property modified , BaseMaterialCard ( list of )

### ISSUE THREAD

**Issue by dikend** [okami101/vtec-admin#2]
**Disclaimer**
Be sure to use the last Vue CLI 4.x version before create the issue.

**Describe the bug**
If necessary precise if it's related to the Admin Library or his Vue CLI plugin.
Write a clear and concise description of what the bug is.

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10 / Ubuntu 18.04]
- Browser with version [e.g. chrome 80, firefox 77]
- Vue CLI version
- Any NPM package version that can be useful as version of Vuetify, Vue I18n, etc.
- Version of Vtec Admin Library or his Vue CLI plugin if applicable [e.g. 0.2.25]

**Additional context**

**Comment by adr1enbe4udou1n** [comment]
Inside `src\locales\en.json` of Vtec Admin library via this key `va.pages.list` "List of {resource}"
You can overwrite it easily by using `resources.titles.list` Vue I18n as key message on your side as [explained here](https://vtec.okami101.io/guide/i18n.html#resources).
